# Generated by Django 3.0.6 on 2020-05-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={},
        ),
    ]
