# Generated by Django 3.0.6 on 2020-05-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200516_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
