# Generated by Django 3.0.6 on 2020-05-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200516_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': True},
        ),
    ]
